apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migration
  namespace: flyway
  annotations:
    #"helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never

      initContainers:
        - name: fetch-migrations
          image: alpine/git:latest
          command: ["/bin/sh", "-c"]
          args:
            - >
              git clone --single-branch --branch main https://github.com/srinadh-cheediri/flyway-helm.git /tmp/ && sleep 10 &&
              cp -r /tmp/flyway-helm/migrations/V*.sql /flyway/sql/ && ls /flyway/sql/ && echo "clonning migration files is sussesfull"

          volumeMounts:
            - name: sql
              mountPath: /flyway/sql

      containers:
        - name: flyway
          image: "{{.Values.flyway.image}}:{{.Values.flyway.tag}}"
          command: ["/bin/sh", "-c"]
          args:
            - >
              flyway
              -url=jdbc:postgresql://$(DB_HOST):5432/$(DB_NAME)
              -user=$(DB_USER)
              -password=$(DB_PASSWORD)
              -locations=filesystem:/flyway/sql
              migrate

          envFrom:
            - secretRef:
                name: db-secret

          volumeMounts:
            - name: sql
              mountPath: /flyway/sql

      volumes:
        - name: sql
          emptyDir: {}
