apiVersion: v1
kind: ConfigMap
metadata:
  name: flyway-sql
data:
{{- $files := .Files.Glob "migrations/*.sql" }}
{{- range $path, $file := $files }}
  {{ base $path }}: |
{{ $file | indent 4 }}
{{- end }}